name: Validate Jira Pull Request

permissions:
  contents: read
  pull-requests: read

on:
#   pull_request:
#     types: [opened, edited, synchronize]
  workflow_dispatch:
    inputs:
      pr_title:
        description: "PR title to validate"
        required: true
        type: string

jobs:
  jira-check:
    uses: transurban/github-action-templates/.github/workflows/jira-check-valid-key-pull-request.yml@Add-New-Github-Rulesets
    # with:
    #   pr_title: ${{ github.event.pull_request.title }}
    with:
      pr_title: ${{ inputs.pr_title }}
    secrets:
      JIRA_USER: ${{ secrets.ATLASSIAN_JIRA_GITHUB_ACTION_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.ATLASSIAN_JIRA_GITHUB_ACTION_API_TOKEN }}
      JIRA_BASE_URL: ${{ secrets.ATLASSIAN_JIRA_BASE_URL }}