name: Dependabot PR → Jira Card

permissions:
  contents: read
  pull-requests: read

on:
#   pull_request:
#     types: [opened]
  workflow_dispatch:
    inputs:
      pr_user_login:
        description: "Simulated PR author login for testing"
        required: false
        type: string

jobs:
  call-dependabot-pr:
    uses: transurban/github-action-templates/.github/workflows/create-jira-card-on-dependabot-pr.yml@Add-New-Github-Rulesets
    with:
      # pr_user_login: ${{ github.event.pull_request.user.login }}
      pr_user_login: ${{ inputs.pr_user_login || (github.event_name == 'pull_request' && github.event.pull_request.user.login) }}
    secrets: 
      JIRA_USER: ${{ secrets.ATLASSIAN_JIRA_GITHUB_ACTION_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.ATLASSIAN_JIRA_GITHUB_ACTION_API_TOKEN }}
      JIRA_BASE_URL: ${{ secrets.ATLASSIAN_JIRA_BASE_URL }}