name: Check Security Alert Age

permissions:
  contents: read
  pull-requests: read

on:
#   pull_request:
#     types: [opened, edited, synchronize]
  workflow_dispatch:

jobs:
  security-check:
    uses: transurban/github-action-templates/.github/workflows/vulnerability-sla-remediation-action.yml@Add-New-Github-Rulesets